my_data<-read.delim("household_power_consumption.txt",sep = ";")
my_df<-my_data[my_data$Date %in% c("1/2/2007","2/2/2007"),]
day<-strptime(paste(my_df$Date,my_df$Time,sep = " "),"%d/%m/%Y %H:%M:%S")
sm1<-as.numeric(my_df$Sub_metering_1)
sm2<-as.numeric(my_df$Sub_metering_2)
sm3<-as.numeric(my_df$Sub_metering_3)
gap<-as.numeric(my_df$Global_active_power)
grp<-as.numeric(my_df$Global_reactive_power)
voltage<-as.numeric(my_df$Voltage)
png("plot4.png",width=480,height = 480)
par(mfrow=c(2,2))
plot(day,gap,type="l",xlab="",ylab = "Global Active Power")
plot(day,voltage,type="l",xlab="",ylab = "Voltage")
plot(day,sm1,col="black",type="l",xlab="",ylab = "Energy sub metering")
lines(day,sm2,type="l",col="red")
lines(day,sm3,type="l",col="blue")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=1,lwd=2.5,col=c("black","red","blue"))
plot(day,grp,type="l",xlab="datetime",ylab = "Global_Reactive_Power")
dev.off()
